import 'kit_strings.dart';

// 繁体字中国語（台湾・香港向け）。機械翻訳の下書き。公開前に、母語話者の確認が要る。
// 用語: 推し=本命 / 学習コイン=學習幣 / 合格=通過。

String _streakDays(int d) => '連續$d天';
String _streakSemantics(int d) => '連續學習 $d 天';
String _correctOfTotal(int c, int t) => '答對 $c / $t 題';
String _passLine(int p) => '及格線 $p%';
String _coinBalance(int b) => '學習幣 $b';
String _wardrobePurchased(String n) => '已購買$n';
String _wardrobePrice(int p) => '$p 學習幣';
String _lockedNotPurchased(int p) => '花 $p 學習幣即可購買';
String _passAskTitle(String c) => '請告訴我們$c的結果';
String _passCoin(int a) => '學習幣 +$a';
String _passOutfit(String n) => '現在可以穿上「$n」了';
String _titleTooLong(int m) => '標題請在 $m 個字以內';
String _detailTooLong(int m) => '詳情請在 $m 個字以內';
String _sourceNote(String s) => '出處：$s';
String _sourceNoteChecked(String s, String d) => '出處：$s（$d 已確認）';
String _mockRecordCert(String c) => '$c 模擬考試';
String _shareDate(DateTime d) => '${d.year}年${d.month}月${d.day}日';
String _aboutVersion(String v) => '版本 $v';

/// 繁体字中国語（`zh-Hant`）。
const kitStringsZhHant = KitStrings(
  languageCode: 'zh-Hant',
  reviewEnjoyTitle: '您喜歡這個應用程式嗎？',
  updateRequiredTitle: '需要更新',
  updateRequiredBody: '此版本已無法使用，請更新至最新版本。',
  updateAvailableTitle: '有新版本',
  updateAvailableBody: '可以更新至最新版本。',
  updateNow: '更新',
  updateLater: '稍後',
  reviewYes: '是',
  reviewNo: '否',
  reviewLater: '稍後',
  purchaseTitle: '購買',
  purchasedPremium: '已購買進階版',
  purchasedNoAds: '已購買移除廣告',
  purchaseRestore: '恢復購買',
  purchaseSuccess: '購買成功。',
  purchaseCancelled: '已取消購買。',
  purchaseBlocked: '無法購買。',
  purchaseFailed: '購買失敗。',
  restoreDone: '已恢復購買。',
  restoreNone: '沒有可恢復的購買項目。',
  examDateTitle: '考試日期',
  examDateUnset: '尚未設定。輸入後即可使用考前複習模式。',
  examDateClear: '清除考試日期',
  settingsTitle: '設定',
  settingsTheme: '顯示模式',
  themeSystem: '跟隨裝置',
  themeLight: '淺色',
  themeDark: '深色',
  settingsLanguage: '語言',
  settingsHandsFree: '單手・邊做邊學',
  handsFreeEnable: '使用單手模式',
  handsFreeSpeakQuestion: '朗讀題目',
  handsFreeSpeakExplanation: '朗讀解析',
  handsFreeSpeed: '朗讀速度',
  settingsTransfer: '學習資料轉移（更換裝置）',
  settingsAbout: '關於本應用程式',
  aboutVersion: _aboutVersion,
  coinTotal: '合計',
  coinBreakdownTitle: '本次獲得的學習幣',
  coinEventLabels: {
    'newQuestion': '新題目',
    'coverageStep': '涵蓋率提升',
    'accuracyMilestone': '達成正確率',
    'accuracyBest': '刷新個人最佳',
    'reviewCorrected': '複習後攻克',
    'dailyConsult': '今日諮詢',
    'mockDone': '完成模擬考試',
    'mockPass': '模擬考試達到及格分',
    'mockBest': '模擬考試個人最佳',
    'streak': '連續學習',
    'passReport': '通過回報',
  },
  errorMessage: '載入失敗。請檢查網路連線後再試一次。',
  retry: '重試',
  streakZero: '從今天開始吧',
  streakDays: _streakDays,
  streakSemantics: _streakSemantics,
  accuracy: '正確率',
  correctOfTotal: _correctOfTotal,
  passLineReached: '已達及格線',
  passLineNotYet: '還差一點。複習一下弱點吧',
  passLine: _passLine,
  again: '再來一次',
  close: '關閉',
  feedbackTitle: '意見回饋・問題回報',
  feedbackType: '類型',
  feedbackBug: '問題回報',
  feedbackFeature: '改善建議',
  feedbackOther: '其他',
  feedbackSubject: '標題',
  feedbackSubjectHint: '例：〇〇頁面的按鈕沒有反應',
  feedbackDetail: '詳情',
  feedbackDetailHint: '請盡量詳細地描述狀況',
  feedbackSubmit: '送出',
  feedbackSent: '已送出，謝謝！',
  feedbackFailed: '送出失敗，請稍後再試。',
  passAskBody: '您告知的內容僅會在這台裝置內使用。',
  passNotYet: '還沒有・等待結果',
  passNotPassed: '這次沒有通過',
  passPassed: '通過了',
  passEncourageTitle: '辛苦了',
  passEncourageBody: '複習弱點後再來挑戰吧。學習幣和服裝都會保留。',
  passCongrats: '恭喜通過',
  passPrivacy: '分享的卡片中不會包含姓名等個人資訊。',
  passShare: '分享',
  wardrobeTitle: '換裝・商店',
  wardrobeNote: '學習幣透過學習獲得。服裝只是外觀，不影響學習內容。',
  wardrobeInsufficient: '學習幣不足。學習即可獲得',
  wardrobeAlreadyOwned: '已擁有',
  wardrobeUnknown: '無法購買',
  wardrobeCannotWear: '目前無法穿上這件服裝',
  wardrobeWear: '穿上',
  wardrobeWearing: '穿著中',
  wardrobeCanWear: '可以穿上',
  lockedNotPassed: '通過考試後解鎖',
  lockedNoExamDate: '設定考試日期後即可穿上',
  lockedNotReady: '達成備考目標後解鎖',
  oshiMenuTooltip: '本命選單',
  oshiChoose: '選擇本命',
  oshiPassReport: '回報考試結果',
  oshiDisplayNormal: '正常',
  oshiDisplaySmall: '縮小顯示',
  oshiDisplayHidden: '不顯示',
  oshiName: '本命',
  oshiHiddenNote: '本命已隱藏',
  oshiYours: '你的本命',
  oshiTapHint: '點一下本命，牠會說句話',
  coinBalance: _coinBalance,
  wardrobePurchased: _wardrobePurchased,
  wardrobePrice: _wardrobePrice,
  lockedNotPurchased: _lockedNotPurchased,
  passAskTitle: _passAskTitle,
  passCoin: _passCoin,
  passOutfit: _passOutfit,
  characterNames: {},
  characterRoles: {
    'standard': '燒瓶助手',
    'kai': '可靠的前輩',
    'mio': '開朗的後輩',
    'moka': '悠閒的夥伴（狗）',
    'mike': '細心的講解員（貓）',
  },
  feedbackTitleRequired: '請輸入標題',
  feedbackDetailRequired: '請輸入詳情',
  feedbackTitleTooLong: _titleTooLong,
  feedbackDetailTooLong: _detailTooLong,
  correctLabel: '正確',
  incorrectLabel: '錯誤',
  sentenceSeparator: '。',
  explanationTitle: '解析',
  tabLabels: ['首頁', '學習', '模擬', '紀錄', '設定'],
  readAloud: '朗讀',
  mockRecordTitle: '學習紀錄卡',
  mockRecordNote: '這是模擬考試的紀錄，並非正式考試通過。不包含姓名等個人資訊。',
  mockRecordMessage: '超過及格分了！',
  sourceNote: _sourceNote,
  sourceNoteChecked: _sourceNoteChecked,
  mockRecordCert: _mockRecordCert,
  shareCardBrand: 'Qualab',
  shareCardPassed: '通過了！',
  shareDate: _shareDate,
);
