import 'kit_strings.dart';

// 韓国語。機械翻訳の下書き。公開前に、母語話者の確認が要る。
// 用語: 推し=최애 / 学習コイン=학습 코인 / 合格=합격。

String _streakDays(int d) => '$d일 연속';
String _streakSemantics(int d) => '연속 학습 $d일';
String _correctOfTotal(int c, int t) => '$t문제 중 $c문제 정답';
String _passLine(int p) => '합격선 $p%';
String _coinBalance(int b) => '학습 코인 $b';
String _wardrobePurchased(String n) => '$n을(를) 구매했습니다';
String _wardrobePrice(int p) => '$p코인';
String _lockedNotPurchased(int p) => '$p코인으로 구매할 수 있어요';
String _passAskTitle(String c) => '$c 결과를 알려 주세요';
String _passCoin(int a) => '학습 코인 +$a';
String _passOutfit(String n) => '이제 「$n」을(를) 입을 수 있어요';
String _titleTooLong(int m) => '제목은 $m자 이내로 입력해 주세요';
String _detailTooLong(int m) => '상세 내용은 $m자 이내로 입력해 주세요';
String _sourceNote(String s) => '출처: $s';
String _sourceNoteChecked(String s, String d) => '출처: $s ($d 확인)';
String _mockRecordCert(String c) => '$c 모의고사';
String _shareDate(DateTime d) => '${d.year}년 ${d.month}월 ${d.day}일';
String _aboutVersion(String v) => '버전 $v';

/// 韓国語（`ko`）。
const kitStringsKo = KitStrings(
  languageCode: 'ko',
  reviewEnjoyTitle: '앱이 마음에 드시나요?',
  updateRequiredTitle: '업데이트가 필요합니다',
  updateRequiredBody: '이 버전은 더 이상 사용할 수 없습니다. 최신 버전으로 업데이트해 주세요.',
  updateAvailableTitle: '새로운 버전이 있습니다',
  updateAvailableBody: '최신 버전으로 업데이트할 수 있습니다.',
  updateNow: '업데이트',
  updateLater: '나중에',
  reviewYes: '네',
  reviewNo: '아니요',
  reviewLater: '나중에',
  purchaseTitle: '구매',
  purchasedPremium: '프리미엄을 구매했습니다',
  purchasedNoAds: '광고 제거를 구매했습니다',
  purchaseRestore: '구매 복원',
  purchaseSuccess: '구매했습니다.',
  purchaseCancelled: '구매를 취소했습니다.',
  purchaseBlocked: '구매할 수 없습니다.',
  purchaseFailed: '구매에 실패했습니다.',
  restoreDone: '구매를 복원했습니다.',
  restoreNone: '복원할 구매 내역이 없습니다.',
  examDateTitle: '시험일',
  examDateUnset: '설정되지 않음. 입력하면 시험 직전 복습 모드를 사용할 수 있어요.',
  examDateClear: '시험일 해제',
  settingsTitle: '설정',
  settingsTheme: '화면 모드',
  themeSystem: '기기 설정에 따름',
  themeLight: '라이트',
  themeDark: '다크',
  settingsLanguage: '언어',
  settingsHandsFree: '한 손・틈틈이 학습',
  handsFreeEnable: '한 손 모드 사용',
  handsFreeSpeakQuestion: '문제 읽어 주기',
  handsFreeSpeakExplanation: '해설 읽어 주기',
  handsFreeSpeed: '읽는 속도',
  settingsTransfer: '학습 데이터 이전 (기기 변경)',
  settingsAbout: '앱 정보',
  aboutVersion: _aboutVersion,
  coinTotal: '합계',
  coinBreakdownTitle: '이번에 모은 학습 코인',
  coinEventLabels: {
    'newQuestion': '새 문제',
    'coverageStep': '커버율 상승',
    'accuracyMilestone': '정답률 달성',
    'accuracyBest': '개인 최고 기록 경신',
    'reviewCorrected': '복습으로 극복',
    'dailyConsult': '오늘의 상담',
    'mockDone': '모의고사 응시',
    'mockPass': '모의고사 합격점',
    'mockBest': '모의고사 개인 최고 기록',
    'streak': '연속 학습',
    'passReport': '합격 보고',
  },
  errorMessage: '불러오지 못했습니다. 네트워크를 확인하고 다시 시도해 주세요.',
  retry: '다시 시도',
  streakZero: '오늘부터 시작해 봐요',
  streakDays: _streakDays,
  streakSemantics: _streakSemantics,
  accuracy: '정답률',
  correctOfTotal: _correctOfTotal,
  passLineReached: '합격선 도달',
  passLineNotYet: '조금만 더! 약점을 복습해 봐요',
  passLine: _passLine,
  again: '다시 하기',
  close: '닫기',
  feedbackTitle: '의견・오류 신고',
  feedbackType: '유형',
  feedbackBug: '오류 신고',
  feedbackFeature: '개선 요청',
  feedbackOther: '기타',
  feedbackSubject: '제목',
  feedbackSubjectHint: '예: 〇〇 화면에서 버튼이 반응하지 않아요',
  feedbackDetail: '상세 내용',
  feedbackDetailHint: '상황을 가능한 한 자세히 알려 주세요',
  feedbackSubmit: '보내기',
  feedbackSent: '보냈습니다. 감사합니다!',
  feedbackFailed: '보내지 못했습니다. 잠시 후 다시 시도해 주세요.',
  passAskBody: '알려 주신 내용은 이 기기 안에서만 사용됩니다.',
  passNotYet: '아직・결과 대기 중',
  passNotPassed: '이번에는 합격하지 못했어요',
  passPassed: '합격했어요',
  passEncourageTitle: '수고하셨어요',
  passEncourageBody: '약점을 복습하고 다시 도전해 봐요. 코인과 의상은 그대로예요.',
  passCongrats: '합격을 축하드려요',
  passPrivacy: '공유하는 카드에는 이름 등 개인 정보가 들어가지 않아요.',
  passShare: '공유하기',
  wardrobeTitle: '의상・상점',
  wardrobeNote: '코인은 학습하면 모여요. 의상은 외형만 바뀌며 학습 내용에는 영향이 없어요.',
  wardrobeInsufficient: '코인이 부족해요. 학습하면 모여요',
  wardrobeAlreadyOwned: '이미 가지고 있어요',
  wardrobeUnknown: '구매할 수 없어요',
  wardrobeCannotWear: '지금은 이 의상을 입을 수 없어요',
  wardrobeWear: '입기',
  wardrobeWearing: '입고 있어요',
  wardrobeCanWear: '입을 수 있어요',
  lockedNotPassed: '합격하면 열려요',
  lockedNoExamDate: '시험일을 설정하면 입을 수 있어요',
  lockedNotReady: '준비 완료 목표를 달성하면 열려요',
  oshiMenuTooltip: '최애 메뉴',
  oshiChoose: '최애 고르기',
  oshiPassReport: '시험 결과 보고',
  oshiDisplayNormal: '보통',
  oshiDisplaySmall: '작게 표시',
  oshiDisplayHidden: '표시 안 함',
  oshiName: '최애',
  oshiHiddenNote: '최애가 숨겨져 있어요',
  oshiYours: '나의 최애',
  oshiTapHint: '최애를 누르면 한마디 해요',
  coinBalance: _coinBalance,
  wardrobePurchased: _wardrobePurchased,
  wardrobePrice: _wardrobePrice,
  lockedNotPurchased: _lockedNotPurchased,
  passAskTitle: _passAskTitle,
  passCoin: _passCoin,
  passOutfit: _passOutfit,
  characterNames: {},
  characterRoles: {
    'standard': '플라스크 조수',
    'kai': '믿음직한 선배',
    'mio': '밝은 후배',
    'moka': '느긋한 짝꿍 (강아지)',
    'mike': '친절한 해설 담당 (고양이)',
  },
  feedbackTitleRequired: '제목을 입력해 주세요',
  feedbackDetailRequired: '상세 내용을 입력해 주세요',
  feedbackTitleTooLong: _titleTooLong,
  feedbackDetailTooLong: _detailTooLong,
  correctLabel: '정답',
  incorrectLabel: '오답',
  sentenceSeparator: '. ',
  explanationTitle: '해설',
  tabLabels: ['홈', '학습', '모의', '기록', '설정'],
  readAloud: '읽어 주기',
  mockRecordTitle: '학습 기록 카드',
  mockRecordNote: '모의고사 기록입니다. 실제 시험 합격이 아닙니다. 이름 등 개인 정보는 들어가지 않아요.',
  mockRecordMessage: '합격점을 넘었어요!',
  sourceNote: _sourceNote,
  sourceNoteChecked: _sourceNoteChecked,
  mockRecordCert: _mockRecordCert,
  shareCardBrand: 'Qualab',
  shareCardPassed: '합격했어요!',
  shareDate: _shareDate,
);
