import 'kit_strings.dart';

// 簡体字中国語。機械翻訳の下書き。公開前に、母語話者の確認が要る。
// 用語: 推し=本命 / 学習コイン=学习币 / 合格=通过。

String _streakDays(int d) => '连续$d天';
String _streakSemantics(int d) => '连续学习 $d 天';
String _correctOfTotal(int c, int t) => '答对 $c / $t 题';
String _passLine(int p) => '及格线 $p%';
String _coinBalance(int b) => '学习币 $b';
String _wardrobePurchased(String n) => '已购买$n';
String _wardrobePrice(int p) => '$p 学习币';
String _lockedNotPurchased(int p) => '花 $p 学习币即可购买';
String _passAskTitle(String c) => '请告诉我们$c的结果';
String _passCoin(int a) => '学习币 +$a';
String _passOutfit(String n) => '现在可以穿上「$n」了';
String _titleTooLong(int m) => '标题请在 $m 个字以内';
String _detailTooLong(int m) => '详情请在 $m 个字以内';
String _sourceNote(String s) => '出处：$s';
String _sourceNoteChecked(String s, String d) => '出处：$s（$d 已确认）';
String _mockRecordCert(String c) => '$c 模拟考试';
String _shareDate(DateTime d) => '${d.year}年${d.month}月${d.day}日';
String _aboutVersion(String v) => '版本 $v';

/// 簡体字中国語（`zh`）。
const kitStringsZhHans = KitStrings(
  languageCode: 'zh',
  reviewEnjoyTitle: '您喜欢这个应用吗？',
  updateRequiredTitle: '需要更新',
  updateRequiredBody: '此版本已无法使用，请更新到最新版本。',
  updateAvailableTitle: '有新版本',
  updateAvailableBody: '可以更新到最新版本。',
  updateNow: '更新',
  updateLater: '稍后',
  reviewYes: '是',
  reviewNo: '否',
  reviewLater: '稍后',
  purchaseTitle: '购买',
  purchasedPremium: '已购买高级版',
  purchasedNoAds: '已购买去广告',
  purchaseRestore: '恢复购买',
  purchaseSuccess: '购买成功。',
  purchaseCancelled: '已取消购买。',
  purchaseBlocked: '无法购买。',
  purchaseFailed: '购买失败。',
  restoreDone: '已恢复购买。',
  restoreNone: '没有可恢复的购买。',
  examDateTitle: '考试日期',
  examDateUnset: '未设置。输入后可使用考前复习模式。',
  examDateClear: '清除考试日期',
  settingsTitle: '设置',
  settingsTheme: '显示模式',
  themeSystem: '跟随设备',
  themeLight: '浅色',
  themeDark: '深色',
  settingsLanguage: '语言',
  settingsHandsFree: '单手・边做边学',
  handsFreeEnable: '使用单手模式',
  handsFreeSpeakQuestion: '朗读题目',
  handsFreeSpeakExplanation: '朗读解析',
  handsFreeSpeed: '朗读速度',
  settingsTransfer: '学习数据迁移（更换设备）',
  settingsAbout: '关于本应用',
  aboutVersion: _aboutVersion,
  coinTotal: '合计',
  coinBreakdownTitle: '本次获得的学习币',
  coinEventLabels: {
    'newQuestion': '新题目',
    'coverageStep': '覆盖率提升',
    'accuracyMilestone': '达成正确率',
    'accuracyBest': '刷新个人最佳',
    'reviewCorrected': '复习后攻克',
    'dailyConsult': '今日咨询',
    'mockDone': '完成模拟考试',
    'mockPass': '模拟考试达到及格分',
    'mockBest': '模拟考试个人最佳',
    'streak': '连续学习',
    'passReport': '通过报告',
  },
  errorMessage: '加载失败。请检查网络后重试。',
  retry: '重试',
  streakZero: '从今天开始吧',
  streakDays: _streakDays,
  streakSemantics: _streakSemantics,
  accuracy: '正确率',
  correctOfTotal: _correctOfTotal,
  passLineReached: '已达及格线',
  passLineNotYet: '还差一点。复习一下薄弱点吧',
  passLine: _passLine,
  again: '再来一次',
  close: '关闭',
  feedbackTitle: '意见反馈・问题报告',
  feedbackType: '类型',
  feedbackBug: '问题报告',
  feedbackFeature: '改进建议',
  feedbackOther: '其他',
  feedbackSubject: '标题',
  feedbackSubjectHint: '例：〇〇页面的按钮没有反应',
  feedbackDetail: '详情',
  feedbackDetailHint: '请尽量详细地描述情况',
  feedbackSubmit: '提交',
  feedbackSent: '已提交，谢谢！',
  feedbackFailed: '提交失败，请稍后再试。',
  passAskBody: '您告知的内容仅在本设备内使用。',
  passNotYet: '还没有・等待结果',
  passNotPassed: '这次没有通过',
  passPassed: '通过了',
  passEncourageTitle: '辛苦了',
  passEncourageBody: '复习薄弱点，再来挑战吧。学习币和服装都会保留。',
  passCongrats: '恭喜通过',
  passPrivacy: '分享的卡片中不会包含姓名等个人信息。',
  passShare: '分享',
  wardrobeTitle: '换装・商店',
  wardrobeNote: '学习币通过学习获得。服装只是外观，不影响学习内容。',
  wardrobeInsufficient: '学习币不足。学习即可获得',
  wardrobeAlreadyOwned: '已拥有',
  wardrobeUnknown: '无法购买',
  wardrobeCannotWear: '目前无法穿上这件服装',
  wardrobeWear: '穿上',
  wardrobeWearing: '穿着中',
  wardrobeCanWear: '可以穿上',
  lockedNotPassed: '通过考试后解锁',
  lockedNoExamDate: '设置考试日期后即可穿上',
  lockedNotReady: '达成备考目标后解锁',
  oshiMenuTooltip: '本命菜单',
  oshiChoose: '选择本命',
  oshiPassReport: '报告考试结果',
  oshiDisplayNormal: '正常',
  oshiDisplaySmall: '缩小显示',
  oshiDisplayHidden: '不显示',
  oshiName: '本命',
  oshiHiddenNote: '本命已隐藏',
  oshiYours: '你的本命',
  oshiTapHint: '点一下本命，它会说句话',
  coinBalance: _coinBalance,
  wardrobePurchased: _wardrobePurchased,
  wardrobePrice: _wardrobePrice,
  lockedNotPurchased: _lockedNotPurchased,
  passAskTitle: _passAskTitle,
  passCoin: _passCoin,
  passOutfit: _passOutfit,
  characterNames: {},
  characterRoles: {
    'standard': '烧瓶助手',
    'kai': '可靠的前辈',
    'mio': '开朗的后辈',
    'moka': '悠闲的搭档（狗）',
    'mike': '细心的讲解员（猫）',
  },
  feedbackTitleRequired: '请输入标题',
  feedbackDetailRequired: '请输入详情',
  feedbackTitleTooLong: _titleTooLong,
  feedbackDetailTooLong: _detailTooLong,
  correctLabel: '正确',
  incorrectLabel: '错误',
  sentenceSeparator: '。',
  explanationTitle: '解析',
  tabLabels: ['首页', '学习', '模拟', '记录', '设置'],
  readAloud: '朗读',
  mockRecordTitle: '学习记录卡',
  mockRecordNote: '这是模拟考试的记录，并非正式考试通过。不包含姓名等个人信息。',
  mockRecordMessage: '超过及格分了！',
  sourceNote: _sourceNote,
  sourceNoteChecked: _sourceNoteChecked,
  mockRecordCert: _mockRecordCert,
  shareCardBrand: 'Qualab',
  shareCardPassed: '通过了！',
  shareDate: _shareDate,
);
